name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install sendgrid
      - name: execute py script # run the run.py to get the latest data
        run: |
          python testes_sendgrid.py
        env:
          key: ${{ secrets.SENDGRID_API_KEY }} # if run.py requires passwords..etc, set it as secrets
